apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  DB_HOST: "minisocial-staging-auth-db.example.us-east-1.rds.amazonaws.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: media-service-config
data:
  S3_BUCKET: "minisocial-staging-media"
