apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  DB_PASSWORD: TWluaVNvY2lhbFN0YWdpbmcxMjMh
  JWT_SECRET: ZGV2c2VjcmV0
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  MYSQL_PASSWORD: cm9vdHBhc3N3b3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
