apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  DB_PASSWORD: UkVQTEFDRV9NRQ==
  JWT_SECRET: UkVQTEFDRV9NRQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  MYSQL_PASSWORD: UkVQTEFDRV9NRQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UkVQTEFDRV9NRQ==
